name = "cloud-mail0417"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "0417"
database_id = "c738afd3-5a1f-461b-aa98-d1fd74936213"

[[kv_namespaces]]
binding = "kv"
id = "86c0fef133d24ac99342af571194860e"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
